### ISSUE TITLE
Iphone test

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/Ushahidi_iPhone#22]
when trying to add a mobile report, I cannot change the location in the dropdown. New Location "Current location" will not deselect.

Should be able to add reports from remote sites without using the phone's location feature. 

Which I click the map to add a location, it won't let me drop a pin on Gowanus Canal (for the gowanuscanal.crowdmap.com)

**Comment by dalezak** [comment]
The new version no longer has list of location, instead will allow user to select location from the map.
