### ISSUE TITLE
Categories, Date and coordinates fields problem

### ISSUE THREAD

**Issue by ghost** [ushahidi/Ushahidi_iPhone#24]
When adding a report the categories and date selector, as well as the coordinates, do not work for me. No matter how i tap, both on horizontal and vertical orientation. iPad2 iOS 5.1

**Comment by dalezak** [comment]
Ah, I know the problem, working on a fix...

**Comment by dalezak** [comment]
A'right, fixed this issue. 

I added some logic to hide the keyboard upon clicking the background of the table, however it was preventing rows from being selectable.

This problem is resolved now.
