### ISSUE TITLE
App crashing on tapping the add new map button

### ISSUE THREAD

**Issue by ghost** [ushahidi/Ushahidi_iPhone#26]
Tapping on the (+) button, in the maps box makes the app crash. Only crashes in vertical orientation.
[tested on iPad2, iOS 5.1]

**Comment by dalezak** [comment]
Assigned to Milestone 2.0.

**Comment by dalezak** [comment]
Looks like a common problem in iOS 5.1.

http://stackoverflow.com/questions/9727917/ios-5-1-uisplitviewcontroller-in-portraitmode-uiactionsheet-in-mastercontrol

**Comment by dalezak** [comment]
Resolved.
