### ISSUE TITLE
Minor layout problem after sending SMS notification

### ISSUE THREAD

**Issue by ghost** [ushahidi/Ushahidi_iPhone#27]
In vertical orientation after sending a Message (iChat) notification the report view is "shorter" (does not take full-height anymore). [on iPad2, iOS 5.1]

**Comment by dalezak** [comment]
Assigned to Milestone 2.0.

**Comment by dalezak** [comment]
Looks, darn Apple going and improving their user experience!

Looks like the new SMS popup dialog is causing the problem...

**Comment by dalezak** [comment]
Resolved.
