### ISSUE TITLE
Persistent error massage of too short text ("high priority bug"!)

### ISSUE THREAD

**Issue by talgalili** [ushahidi/Ushahidi_iPhone#37]
The problem: after making the error of entering too short a massage - the app keeps throwing error massages, even when submitting proper reports.

Steps to reproduce the bug:
1) Use the iphone app to report a bug to an ushahidi 2.4 instance. Make sure the title or subject are too short (less than 3 characters) and submit the report.
2) An error massage will pop up "the report title field must be at least 2 and...." - click ok (it will repeat the error 3 times, at least it did for me)
3) Now submit a valid report (with a long enough title) - the error massage will keep poping up (although the report itself will actually be sent)

Moving to another map and back doesn't resolve this.
Restarting the app doesn't resolve this.
Uninistalling and re installing the app does resolve this.

**Comment by talgalili** [comment]
bump?!

**Comment by dalezak** [comment]
This problem is fixed in the upcoming version of Ushahidi iOS app...closing issue.
