### ISSUE TITLE
Allow reports with no category

### ISSUE THREAD

**Issue by rediguana** [ushahidi/Ushahidi_iPhone#39]
(feature request) As per issue #38 Invalid Server Response loading categories, I have discovered that it is impossible to submit a report unless a category is assigned. I would like to suggest that is it more important that reports with no categories are received, than no reports at all because it is not possible to assign a category. Categories can always be assigned by the back-end personal managing the deployment.

**Comment by dalezak** [comment]
Unfortunately, the API currently requires a category we provided in the HTTP POST.

Being a client of the API, the mobile apps are at the mercy of the backend, therefore require category is provided.
