### ISSUE TITLE
Use iOS Share approach

### ISSUE THREAD

**Issue by rediguana** [ushahidi/Ushahidi_iPhone#40]
It would be good to see the means of 'sharing' a report updated to use a more common approach on the iOS platform. A single share icon (the rectangle with arrow) could be used to share a report using Facebook, Twitter, email etc rather than the existing bubble, bird and email. Naturally, the Twitter support could be upgraded to utilise the iOS Twitter support so it isn't necessary to configure Twitter in the Ushahidi iPhone client if the user has opted to use Twitter device-wide.

**Comment by dalezak** [comment]
The new Ushahidi iOS 3.0 (in development) uses the standard iOS Twitter and Facebook sharing, and also provides sharing via email, sms, QR Code and printing.
