### ISSUE TITLE
White Label with multiple maps

### ISSUE THREAD

**Issue by dkobia** [ushahidi/Ushahidi_iPhone#47]
It would be nice to white label with multiple map urls and possibly define the map labels/titles as well. To give you a better idea of what I'm trying to do... For MapATL.com, I'm in the process of creating other Atlanta maps and I'm trying to avoid having to create separate apps for each map.

**Comment by dalezak** [comment]
That's a good idea! 

Perhaps in the PList I could allow an array of map URLs, rather than just a single URL.

This could be very useful for an organization like Huffington Post or Al Jezeera.

**Comment by dkobia** [comment]
Exactly Dale!

**Comment by dalezak** [comment]
Actually, this would also be a good way to define the default deployment, http://demo.ushahidi.com in the actual app.

Adding this functionality this morning, so it will be included in Ushahidi iOS 3.0 release this week.

**Comment by dalezak** [comment]
Screenshot http://o7.no/11Uluya
