### ISSUE TITLE
Deployment does not show in android device when going to "Find Maps Arround Me"

### ISSUE THREAD

**Issue by EUNACAL** [ushahidi/Ushahidi_iPhone#49]
I have set up an ushahidi deployment. I try to access it from my android device going to "Find Maps Arround Me" but the deployment does not show. Any idea why?

**Comment by dalezak** [comment]
Is this an Android or iOS issue?

For maps to be visible in the mobile maps, you need to enable Public Listing.

/admin/manage/publiclisting

**Comment by EUNACAL** [comment]
Thank you Dale, 
it is an Android issue. You are right, public listing was not active. Now it is active and the map show on "Find Maps Arround Me" but it says "there are no reports to be shown". The deployment is www.raportime.com and there are about 100 reports on it. Any idea on the solution.
Cheers from Tirana, Albania
from Alban (Vilnius TechCamp 2011)

**Comment by dalezak** [comment]
Thanks for reporting this problem with the Android app.

Can you please create an issue on https://github.com/ushahidi/ushahidi_android/issues?
