### ISSUE TITLE
Loading issues

### ISSUE THREAD

**Issue by aoduor** [ushahidi/Ushahidi_iPhone#52]
No description was given by the guy who sent in the bug report, but he sent in an image:-

![screenshot](http://i.imgur.com/VDSdgTj.png)

**Comment by dalezak** [comment]
This problem will be resolved in Ushahidi iOS 3.2 which was just submitted to the App Store.

During the initial sync the app now checks api?task=version replacing the user entered server url with one from 'domain' value which will have https:// is SSL is supported.
