### ISSUE TITLE
Ushahidi 3.1 - my map is not found

### ISSUE THREAD

**Issue by MapperBob** [ushahidi/Ushahidi_iPhone#53]
NOTE: this issue has also been posted under General Questions at: http://help.ushahidi.com/discussions/questions/7090-ushahidi-31-my-map-is-not-found?anon_token=f63ccee3391dbf271bdd8b7450f461956dc4e82b

My website is: winnipegmuralsnews.crowdmap.com

My Ushahidi iPhone client is not finding this site when I do a geographical search from my location here in Winnipeg, Manitoba.

I have set up the map and see the correct latitude and longitude listed on the map page, however this isn't displayed on the public listing page. Is this why my iPhone client isn't finding the website? How would I get crowdmap to use the position that I have set on my website's map as the map center on my public listing?

Thanks, 
               Bob Bruce 

Version: Ushahidi 3.1 
Model: iPhone 6.1

**Comment by dalezak** [comment]
Hey Bob,

Just did a search for your map via tracker service and looks like the latitude and longitude is not set correctly, which is why its not showing in the app.

http://tracker.ushahidi.com/list/?q=Winnipeg

{
49025: {
id: "49025",
name: "News About Winnipeg Murals",
url: "https://winnipegmuralsnews.crowdmap.com/",
description: "People can use this website to report news about the changes to the murals of Winnipeg",
category_id: "1",
latitude: "0",
longitude: "0",
discovery_date: "2013-01-08 06:58:06",
ss1: null,
ss2: null,
ss3: null,
ss4: null,
ss5: null,
ss1_t: null,
ss2_t: null,
ss3_t: null,
ss4_t: null,
ss5_t: null,
distance: null
}
}

Can you please double check the center of your map it set to Winnipeg?

**Comment by MapperBob** [comment]
Dale and Angela, 

                thanks for your help. This is the second time that I have got help from you guys in a week! (the first time was when the iPhone app was gone from the App store and you got it back) 

           O n my map page the latitude and longitude are shown as: 49.89558015886456,-97.13838816201834. W hen I adjust this point the values are not copied over to the public listing page. I wonder if this is what is causing the problem. Shouldn't the coordinates that are set on the Map page be the ones that are displayed on the Public Listing page? Originally I didn't set the site up as a public listing, I changed that once I was satisfied that I had it the way that I wanted it. I wonder if that is what was causing the coordinates to not be carried over. 

Your excellent user support will definitely be part of my presentation at the MGUG meeting this Friday ( http://mgug.ca/sites/all/themes/mgug/docs/agenda/MGUG_Workshop_2013.pdf ) 
https://github.com/ushahidi/Ushahidi_iPhone/issues/53 

I'm hoping that this can be fixed so that when I stand up and give my presentation on Friday, the audience members who have iPhones who will immediately get on them and search for the site will find it. 

I can certainly add the site via its URL though. 

Your open-source project and support is great, I have been involved with using MapServer and QGIS as a user often seeking help from their developers and you are right up there with their support. 

thanks again, 
             Bob Bruce ( http://www.hwps.ca/ ) 

----- Original Message -----

**Comment by MapperBob** [comment]
# // Add your reply above here

From: AngelaO
Subject: Ushahidi 3.1 - my map is not found

Hey Bob,

You may have to edit/resvae your public listing details via your admin panel for it to reflect on the main public listing page. You can do this via admin/manage/publiclisting. Try that out and let us know how it goes?

Also hoping this can get fixed as soon as possible, before your presentation on Friday. 

All the best :).

Angie

View this Discussion online: http://help.ushahidi.com/discussions/questions/7090-ushahidi-31-my-map-is-not-found?anon_token=f63ccee3391dbf271bdd8b7450f461956dc4e82b

## This discussion is PRIVATE. Please don't share your secret link with anyone.

Reply with #ignore to stop receiving notifications for this discussion.

**Comment by MapperBob** [comment]
# // Add your reply above here

From: Bob Bruce
Subject: Ushahidi 3.1 - my map is not found

Angela,
       nothing that I do seems to get the coordinates from my map page transferred to the public listing page. I have now changed the coordinates of the marker on the map to 49.89549031149289  -97.13847399271101 and changed the map view to OSM Mapnik and it still didn't transfer the coordinates over. When I resave my map setup and resave my public listing the new map is shown on the website so some of the map settings are saved.

For the time being, I'm going to leave the map as the OSM one. The public listing has been saved so when you go to the site you will see that map.

thanks,
       Bob

View this Discussion online: http://help.ushahidi.com/discussions/questions/7090-ushahidi-31-my-map-is-not-found?anon_token=f63ccee3391dbf271bdd8b7450f461956dc4e82b

## This discussion is PRIVATE. Please don't share your secret link with anyone.

Reply with #ignore to stop receiving notifications for this discussion.

**Comment by MapperBob** [comment]
# // Add your reply above here

From: AngelaO
Subject: Ushahidi 3.1 - my map is not found

Hi Bob,

So sorry for the inconvenience caused by this.
We are now aware and are looking into fixing this. See below:-

https://github.com/ushahidi/Ushahidi_Web/issues/1019

Hope everything else goes well!

Best,
Angela

View this Discussion online: http://help.ushahidi.com/discussions/questions/7090-ushahidi-31-my-map-is-not-found?anon_token=f63ccee3391dbf271bdd8b7450f461956dc4e82b

## This discussion is PRIVATE. Please don't share your secret link with anyone.

Reply with #ignore to stop receiving notifications for this discussion.

**Comment by MapperBob** [comment]
# // Add your reply above here

From: Bob Bruce
Subject: Ushahidi 3.1 - my map is not found

Thanks Angela, that's much appreciated. My MGUG presentation on Friday was well received, the Internet connection went down on me but luckily I had slides of everything except the main video on the Ushahidi website that I had wanted to play.

I am getting a POST error when I try and enter reports from my iPhone, has this already been reported? Is is an error in the app or at the server end? Should I report it and if so then where?

Thanks,
              Bob Bruce

Sent from my iPhone

View this Discussion online: http://help.ushahidi.com/discussions/questions/7090-ushahidi-31-my-map-is-not-found?anon_token=f63ccee3391dbf271bdd8b7450f461956dc4e82b

## This discussion is PRIVATE. Please don't share your secret link with anyone.

Reply with #ignore to stop receiving notifications for this discussion.

**Comment by MapperBob** [comment]
# // Add your reply above here

From: AngelaO
Subject: Ushahidi 3.1 - my map is not found

Hi Bob,

You need to make sure your deployment URL is https:// instead of http://

Try that and let me know how it goes?

Best,
Angela

View this Discussion online: http://help.ushahidi.com/discussions/questions/7090-ushahidi-31-my-map-is-not-found?anon_token=f63ccee3391dbf271bdd8b7450f461956dc4e82b

## This discussion is PRIVATE. Please don't share your secret link with anyone.

Reply with #ignore to stop receiving notifications for this discussion.

**Comment by MapperBob** [comment]
# // Add your reply above here

From: Bob Bruce
Subject: Ushahidi 3.1 - my map is not found

Angela,
       thanks, this fixed my problem for sure. It's too bad that the iPhone app doesn't put in the https:// when it adds the map. It defeats the usefulness of doing a geographical search and adding a site if you have to delete it and manually add it via a URL. It's a thought that occured to me as I was doing this.

It looks like the problem with the coordinates has been fixed, I even see it fixed on my experimental site: https://manitobaroadkills.crowdmap.com/ 

I met tonight with the manager of www.themuralsofwinnipeg.com to talk about this mapping site. Some ideas of how to improve the crowdmap.com site occured to us, where is the right place to make some suggestions?

thanks for all of your help so far,
                                    Bob Bruce

View this Discussion online: http://help.ushahidi.com/discussions/questions/7090-ushahidi-31-my-map-is-not-found?anon_token=f63ccee3391dbf271bdd8b7450f461956dc4e82b

## This discussion is PRIVATE. Please don't share your secret link with anyone.

Reply with #ignore to stop receiving notifications for this discussion.

**Comment by dalezak** [comment]
Hey Bob,

I'll fix this HTTP vs HTTPS issue in the next version, looks like the problem only arose in the most recent version of Crowdmap.

I would default to https:// in the URL input field, however other non-Crowdmap deployments often don't support SSL so their sync would fail.

For the fix, I'll try to hit https://[DEPLOYMENT_URL]/api?task=version and if I receive back a response that means their deployment supports SSL so will default to using that, otherwise will call back to HTTP.

**Comment by dalezak** [comment]
Closing issue.

**Comment by MapperBob** [comment]
Thanks Dale, that sounds like it ought to do the trick.

```
  Bob
```

Sent from my iPhone

On 2013-02-25, at 11:13 PM, Dale Zak notifications@github.com wrote:

Hey Bob,

I'll fix this HTTP vs HTTPS issue in the next version, looks like the problem only arose in the most recent version of Crowdmap.

I would default to https:// in the URL input field, however other non-Crowdmap deployments often don't support SSL so their sync would fail.

For the fix, I'll try to hit https://[DEPLOYMENT_URL]/api?task=version and if I receive back a response that means their deployment supports SSL so will default to using that, otherwise will call back to HTTP.
