### ISSUE TITLE
Map URL should default to https as opposed to http for crowdmap deployments

### ISSUE THREAD

**Issue by aoduor** [ushahidi/Ushahidi_iPhone#54]
Several deployers have been having issues posting to their crowdmaps from the iOS app because of this.

**Comment by dalezak** [comment]
This problem will be resolved in Ushahidi iOS 3.2 which was just submitted to the App Store.

During the initial sync the app now checks api?task=version replacing the user entered server url with one from 'domain' value which will have https:// is SSL is supported.
