### ISSUE TITLE
ios got data "wos not send by method"

### ISSUE THREAD

**Issue by sipgear** [ushahidi/Ushahidi_iPhone#55]
![ PNG 5B1 5D 1 ](https://f.cloud.github.com/assets/3627615/183943/f845b12e-7cc2-11e2-88ed-f640fc861217.jpg)
![ PNG 5B1 5D](https://f.cloud.github.com/assets/3627615/183944/f877dcb2-7cc2-11e2-8c1b-5bf9880c909f.jpg)

**Comment by sipgear** [comment]
add report to http://muji.crowdmap.com

**Comment by dalezak** [comment]
This problem will be resolved in Ushahidi iOS 3.2 which was just submitted to the App Store.

During the initial sync the app now checks api?task=version replacing the user entered server url with one from 'domain' value which will have https:// is SSL is supported.
