### ISSUE TITLE
Applications crashes when edit photo in a report.

### ISSUE THREAD

**Issue by junixbr** [ushahidi/Ushahidi_iPhone#62]
Applications crashes when try to edit a photo in a report, when this photo is from photo gallery.

**Comment by dalezak** [comment]
Hmm, I'm unable to reproduce this problem, any other information you can provide to help recreate it?

**Comment by junixbr** [comment]
For example:
1- I start a report
2- I get a picture from camera roll
3- I upload the report
4- When I check the report, there is no photo
5- When I try to edit the report and touch on the picture, the application crashes.

**Comment by dalezak** [comment]
Hi Alfredo, what version of the app are you running? 

The Ushahidi iOS 3.X app does not allow editing of reports, so I'm confused by step 5.

**Comment by junixbr** [comment]
I don't know why, but in my ushahidi iPhone app when I create a report, it duplicates in my phone after validation/approbal.
The first report in my list has no validation/approbal and you can edit.

**Comment by dalezak** [comment]
Hi Alfredo, I pushed some changes which hopefully fixes the problem, although I've still been unable to reproduce the issue so can't verify myself.

I'll leave the issue open, once Ushahidi iOS 3.5 gets approved, can verify whether it fixes your problem?

**Comment by junixbr** [comment]
Thank you dalezak, lets wait the next release.

**Comment by dalezak** [comment]
Hey Alfredo, can you please test the new version 3.5?

https://itunes.apple.com/ca/app/ushahidi/id410609585

**Comment by junixbr** [comment]
Thank you very much dalezak.
Now is perfect!
I'll close this issue.
