### ISSUE TITLE
IOS: coordinate correction doesn't work

### ISSUE THREAD

**Issue by mms101** [ushahidi/Ushahidi_iPhone#64]
Hello,

When I tried to correct coordinates for a report with Ushahidi application on iPhone, the application get coordinates of current position.

So, when I wish to create report, when I’m not in place of report, I’m not able to input right position.

iPhone: 5

IOS: 6.1.4 (10B350)

Regards,

Modest Sokolov

**Comment by dalezak** [comment]
If you click the latitude & longitude row for a new report, it will show a clickable map which allows you to move the map pin.

![ushahidi_ios_map](https://f.cloud.github.com/assets/91811/599806/f124ae28-cc58-11e2-8378-c78998af7f5b.jpg)

**Comment by mms101** [comment]
Hello,

That's right. I've used this way, but corrections on the map it was not
changed on the position.
Hope, it is fixed now.

2013/6/3 Dale Zak notifications@github.com

**Comment by dalezak** [comment]
Ok, I'll investigate...

**Comment by sselbe** [comment]
Yeah we are having that problem as well on our whitelabeled version of the app. It is not allowing any location other than the current one. Pin will drop and show the new coordinates, but once you return to the report page it will just revert back to the current location.

**Comment by dalezak** [comment]
A'right, added a check to only detect location if the report latitude or longitude has not been set, this will prevent the current location from clobbering the user's newly selected location.

The fix will be included in the 3.6 release of the Ushahidi iOS app.
