### ISSUE TITLE
Unable to add map on IOS7 beta

### ISSUE THREAD

**Issue by stevevg** [ushahidi/Ushahidi_iPhone#69]
The "add new map" dialog shows as follows.
![img_1724 1](https://f.cloud.github.com/assets/2536019/932041/d29bf4f2-0038-11e3-8f64-1b5b636c79c4.PNG)

This happened on all betas <= 5

**Comment by dalezak** [comment]
Thanks for reporting this, I'll include a fix in the next version.

**Comment by TomCor** [comment]
When the next version will be realeased ?

**Comment by Luki1** [comment]
I have exactly the same problem. It makes the whole app pretty useless unfortunately... :(
Does anyone know of a workaround until this problem will be solved?

**Comment by dalezak** [comment]
I'll work on a fix and push an update this week.

**Comment by dalezak** [comment]
![ushahidi_add_map_2](https://f.cloud.github.com/assets/91811/1559560/ecc6fb30-4fd7-11e3-91c5-81870112aa6f.jpg)

Just pushed a fix for this, will include it in Ushahidi iOS 3.7 update.
