### ISSUE TITLE
App not working - Demo map continiusly syncing

### ISSUE THREAD

**Issue by gcameron89777** [ushahidi/Ushahidi_iPhone#70]
Iphone 4s running on 6.1.2. If you download the Ushahidi app and then try to open it, the demo map syncs indefinitely. All other controls are grayed out and the gif wheel spins. You cannot actually use the app while it is syncing, but it syncs indefinatley.

This was brought to my attention by a visitor to my site. I deleted the existing Ushahidi app on my phone and re-downloaded to see if I could recreate the issue - sure enough I am unable to use the Ushahidi app and am experiencing the same problem.

**Comment by dalezak** [comment]
Thanks for reporting this, however it doesn't look like a problem with the app but rather with the API :(

The mobile app is making the API call to the Demo Map [http:/demo.ushahidi.com/api?task=incidents&by=all&resp=json&comments=1&limit=25](http:/demo.ushahidi.com/api?task=incidents&by=all&resp=json&comments=1&limit=25)

Unfortunately there is a bug which is allowing excessive amount of spam to get through. All these spam messages are sadly being returned via the API which means the mobile app needs to download them all.

I just tested in the simulator and the Demo Map successfully downloaded the last 25 reports, however even on a fast broadway connection, it took a very long time to sync.

![ushahidi](https://f.cloud.github.com/assets/91811/935463/c02283c6-0084-11e3-9cfc-c4cd7c15672c.jpg)

![ushahidi-spam](https://f.cloud.github.com/assets/91811/935485/56b837ae-0085-11e3-9cc9-15c7f3dc9d91.jpg)

I'll let the team know to see if they can delete these reports from the Demo Map and hopefully patch this spam bug.

**Comment by gcameron89777** [comment]
Thanks for the info @dalezak. Hoping something can be done. That's make sense being API rather than app itself as someone in Germany just contacted me to say they are having a similar issue with Android.

**Comment by dalezak** [comment]
Closing issue.
