### ISSUE TITLE
IOS7: Impossible to add a map by URL

### ISSUE THREAD

**Issue by bobbex** [ushahidi/Ushahidi_iPhone#71]
Hi, 
no field to enter the URL, impossible to enter a new map.
It was working fine before the IOS update ... Behavior looks like the issue 69, same screenshot. 

Thank you,

Bobbex

**Comment by TomCor** [comment]
Same issue, really problematic ...

**Comment by ramotswa** [comment]
+1 on this... really quite important!

**Comment by suncommon** [comment]
I agree; this is an important issue.

**Comment by dalezak** [comment]
Got it!

![ushahidi_add_map](https://f.cloud.github.com/assets/91811/1559526/997d2964-4fd6-11e3-8425-796f1af5cdeb.jpg)

**Comment by dalezak** [comment]
And even better!

![ushahidi_add_map_2](https://f.cloud.github.com/assets/91811/1559548/56c079a4-4fd7-11e3-8190-d98fd22116b6.jpg)

**Comment by dalezak** [comment]
Just pushed a fix for this, will include it in Ushahidi iOS 3.7 update.
