### ISSUE TITLE
How increase records limit > 250?

### ISSUE THREAD

**Issue by suncommon** [ushahidi/Ushahidi_iPhone#72]
Hello. The max is 250 for records downloaded. How do I increase this? The app is not usable with this limit; users need to be able to see all 600(ish) records. Thanks!

Kevin

**Comment by dalezak** [comment]
Increased download limit to 500.

**Comment by suncommon** [comment]
Thank you for increasing limit, but 500 not sufficient for us. Could you increase it to 1000, please. Thanks!
