### ISSUE TITLE
Stuck in add report

### ISSUE THREAD

**Issue by isaaclimdc** [ushahidi/Ushahidi_iPhone#87]
When clicking on the camera button to add a new report, the modal screen below comes up, with no way to leave.

![screen shot 2014-04-23 at 2 05 12 am](https://cloud.githubusercontent.com/assets/756308/2774034/41e49a96-caad-11e3-8263-ff3377b12ff5.png)

**Comment by isaaclimdc** [comment]
@dkobia this is fixed; you can close it.

**Comment by dkobia** [comment]
closed by b1ad28d
